StoreX/urls.py
from django.contrib import admin
from django.urls import path, include

# Media reading configurations.
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

# Media We are here serving static files through the development server.
# NOTE: Upon deployment, we will serve static files in different approach.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

from shop.models import Product


# Model contains order details
class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)  # To differentiate if this order is paid or not.

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


# Model contains orders bought
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


# Creating the category table
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    # Meta allows us to override elements in our class
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]

        verbose_name = 'category'
        verbose_name_plural = 'categories'

    # To View the class name on admin
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    # Foreign Key Category that links products with it's category table.
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)  # Slugs are used to build beautiful URLs.
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        # Order based on latest created products
        ordering = ['created']
        # Orders based index to get data fast using B-Tree indexes data structure
        # https://www.youtube.com/watch?v=kv3jC0P4gOc
        indexes = [
            models.Index(fields=['id', 'slug']),  # Query products by both "id" and "slug".
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
"""
1. User Form.
2. Order Instance.
3. Clear cart's content -> redirect to success page.
"""
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from cart.cart import Cart
from orders.forms import OrderCreateForm
from orders.models import OrderItem


# View > Handle Form & Create Order
def order_create(request):
    # Get info of current cart from session.
    cart = Cart(request)
    if request.method == 'POST':
        # Request Payment Form
        form = OrderCreateForm(request.POST)
        # If all data are valid - Save it
        if form.is_valid():
            order = form.save() # if valid - create new order in DB.
            # Loop over the order and each product, price, and quantity of item.
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['price'], quantity=item['quantity'])
            cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddProductForm
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    # return render(request, 'shop/product/detail.html', {'product': product}) THIS CODE IS LEFT FOR MEMORY OF 5Hrs BUG!
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Your shopping cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Remove" %}</th>
        <th>{% trans "Unit price" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "images/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="{% trans "Update" %}">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="{% trans "Remove" %}">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
              "{{ code }}" coupon ({{ discount }}% off)
            {% endblocktrans %}
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>

  {% if recommended_products %}
  <div class="recommendations cart">
    <h3>{% trans "People who bought this also bought" %}</h3>
    {% for p in recommended_products %}
      <div class="item">
        <a href="{{ p.get_absolute_url }}">
          <img src="{% if p.image %}{{ p.image.url }}{% else %}
          {% static "images/no_image.png" %}{% endif %}">
        </a>
        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
      </div>
    {% endfor %}
  </div>
{% endif %}

{#  <p>{% trans "Apply a coupon" %}:</p>#}
{#  <form action="{% url "coupons:apply" %}" method="post">#}
{#    {{ coupon_apply_form }}#}
{#    <input type="submit" value="{% trans "Apply" %}">#}
{#    {% csrf_token %}#}
{#  </form>#}
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">{% trans "Continue shopping" %}</a>
    <a href="{% url 'orders:order_create' %}" class="button">{% trans "Checkout" %}</a>
  </p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}

     <h1>Checkout</h1>

     <div class="order-info">
         <h3>Your order</h3>
         <ul>
             {% for item in cart %}
             <li>
                 {{ item.quantity }}x {{ item.product.name }}
                 <span>${{ item.total_price }}</span>
             </li>
             {% endfor %}
         </ul>
         <p>Total: ${{ cart.get_total_price }}</p>
     </div>

     <form method="post" class="order-form">
         {{ form.as_p }}
         <p><input type="submit" value="Place order"></p>
         {% csrf_token %}
     </form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %} Thank you {% endblock %}


{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}StoreX{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        <link href="{% static "css/pdf.css" %}" rel="stylesheet">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>

    <body>
        <div id="header">
            <a href="/" class="logo">StoreX</a>
        </div>

        <div id="subheader" class="d-flex justify-content-end">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    <span>Your cart:
                        <a href="{% url "cart:cart_detail" %}">
                             {{ total_items }} item{{ total_items|pluralize }}
                            ${{ cart.get_total_price }}
                        </a>
                    </span>
                {% elif not order %}
                    <span>Your cart: 0 items</span>
                {% endif %}
            {% endwith %}
        </div>


        <div id="content">
            {% block content %}
            {% endblock %}
        </div>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>

        <h2>
            <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
        </h2>

        <p class="price">${{ product.price }}</p>

        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {{ CartAddProductForm }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>

        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}


{% block title %}
    {% if category %} {{ category.name }} {% else %} Products {% endif %}
{% endblock title %}

{% block content %}
     <div id="sidebar">
         <h3>Categories</h3>

         <ul>
             <li {% if not category %} class="selected" {% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
             </li>

             {% for c in categories %}
                <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
             {% endfor %}
         </ul>

     </div>


     <div id="main" class="product-list">
         <h1>{% if category %}
             {{ category.name }}
         {% else %}
             Products
         {% endif %}</h1>

         {% for product in products %}
             <div class="item">
                 <a href="{{ product.get_absolute_url }}">
                    <img class="bx_shadow" src="{% if product.image %} {{ product.image.url }} {% else %} {% static "images/no_image.png" %}{% endif %}">
                 </a>

                <div class="item-txt">
                     <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                     <br>
                     ${{ product.price }}
                </div>
             </div>
         {% endfor %}
     </div>

{% endblock %}